// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by scripts/generate-print-styles.cjs

export const GENERATED_CORE_STYLES = `
/* Source: src/styles/editor.css */
.native-editor-container,
#editor-container {
    --bg-color: #ffffff;
    --text-color: #000000;
    --accent-color: #007AFF;
    --placeholder-color: rgba(0, 0, 0, 0.4);
    --code-bg: rgba(0, 0, 0, 0.06);
    --quote-bg: rgba(0, 0, 0, 0.06);
    --code-block-bg: #F5F5F5;
    --border-color: rgba(0, 0, 0, 0.15);
    --table-header-bg: rgba(33, 33, 33, 0.371);
    --table-cell-min-width: 32px;
    --table-cell-default-width: 104px;
    --editor-font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    --editor-font-size: 16px;
    --editor-line-height: 1.5;
    --editor-paragraph-spacing: 8px;
    --editor-list-item-spacing: 2px;
    --editor-max-width: 100%;
    --editor-padding-top: 0px;
}

@media (prefers-color-scheme: dark) {

    .native-editor-container,
    #editor-container {
        --bg-color: color-mix(in srgb, var(--card, #171717), transparent 50%);
        --text-color: rgba(255, 255, 255, 0.85);
        --placeholder-color: rgba(255, 255, 255, 0.4);
        --code-bg: rgba(255, 255, 255, 0.1);
        --quote-bg: rgba(255, 255, 255, 0.1);
        --code-block-bg: #232323;
        --border-color: rgba(255, 255, 255, 0.2);
        --table-header-bg: rgba(255, 255, 255, 0.1);
    }
}

@font-face {
    font-family: 'Poppins';
    src: url('../assets/fonts/Poppins/Poppins-Regular.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'FiraCode';
    src: url('../assets/fonts/FiraCode/FiraCode-VF.ttf') format('truetype');
    font-weight: 300 700;
    font-style: normal;
    font-display: swap;
}


* {
    box-sizing: border-box;
    -webkit-tap-highlight-color: transparent;
}

/* Base Styles - only for editor containers */
.native-editor-container,
#editor-container {
    margin: 0;
    padding: 0;
}

.native-editor-container,
#editor-container,
.ProseMirror {
    background-color: var(--bg-color);
    color: var(--text-color);
    font-family: var(--editor-font-family);
    font-size: var(--editor-font-size);
    line-height: var(--editor-line-height);
    -webkit-text-size-adjust: 100%;
    white-space: pre-wrap;
    /* Required for ProseMirror cursor and space handling */
    word-break: break-word;
    min-width: 0;
}

/* Custom Scrollbar */
::-webkit-scrollbar {
    width: 6px;
    height: 6px;
}

::-webkit-scrollbar-track {
    background: transparent;
}

::-webkit-scrollbar-thumb {
    background: var(--border-color);
    border-radius: 10px;
    border: 2px solid var(--bg-color);
}

::-webkit-scrollbar-thumb:hover {
    background: var(--accent-color);
    opacity: 0.8;
}

/* Firefox support */
* {
    scrollbar-width: thin;
    scrollbar-color: var(--border-color) transparent;
}

#editor-container {
    padding: 0;
    padding-bottom: 80px;
    min-height: 100vh;
    position: relative;
    /* clip prevents horizontal scrollbar without creating a scroll container.
       overflow-x:hidden would clip position:absolute children (the drag handle)
       because it creates a new BFC that acts as a containing block. */
    overflow-x: clip;
    container-type: inline-size;
}

#loading {
    padding: 20px;
    text-align: center;
    color: var(--placeholder-color);
}

/* Edit mode - TipTap editor */
#editor-content {
    outline: none;
    min-height: calc(100vh - 100px);
    max-width: var(--editor-max-width);
    margin-left: auto;
    margin-right: auto;
}

/* Hidden state */
#editor-content.hidden {
    display: none;
}


/* ProseMirror Styles matched to old Display Mode for consistency */

.ProseMirror {
    outline: none;
    min-height: calc(100vh - 100px);
    font-family: var(--editor-font-family);
    font-size: var(--editor-font-size);
    padding-top: var(--editor-padding-top);
    padding-bottom: 200px;
    padding-left: 16px;
    padding-right: 16px;
    -webkit-user-drag: auto;
    white-space: pre-wrap;
    /* Essential for correct cursor placement */
    caret-color: var(--accent-color);
    /* Safe bottom margin inside editor */
}

/* Remove top margin from the very first element to allow precise positioning via header/tags */
.ProseMirror>*:first-child {
    margin-top: 0 !important;
}

.ProseMirror-dropcursor {
    border-left: 2px solid var(--accent-color) !important;
}

.ProseMirror strong,
.ProseMirror b {
    font-weight: 600;
}

.ProseMirror p {
    margin: 0 !important;
    padding-top: calc(var(--editor-paragraph-spacing) * 0.5) !important;
    padding-bottom: calc(var(--editor-paragraph-spacing) * 0.5) !important;
    unicode-bidi: plaintext;
    text-align: start;
    min-height: 1.1em;
    font-size: var(--editor-font-size);
    line-height: var(--editor-line-height);
}

.ProseMirror ul {
    list-style-type: disc;
    padding-inline-start: 24px;
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
}

.ProseMirror ul ul,
.ProseMirror ol ul,
.ProseMirror ul ul li,
.ProseMirror ol ul li {
    list-style-type: circle !important;
}

.ProseMirror ul ul ul,
.ProseMirror ol ul ul,
.ProseMirror ul ul ul li,
.ProseMirror ol ul ul li {
    list-style-type: square !important;
}

.ProseMirror ol {
    list-style-type: decimal;
    padding-inline-start: 24px;
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
}

.ProseMirror li {
    margin: 0;
    margin-bottom: var(--editor-list-item-spacing);
    unicode-bidi: plaintext;
    text-align: start;
}

.ProseMirror li:last-child {
    margin-bottom: 0;
}

.ProseMirror li::marker {
    color: var(--accent-color);
}


.ProseMirror li p {
    margin: 0;
    unicode-bidi: plaintext;
    text-align: start;
}

/*
 * When direction is explicitly set (not auto), switch unicode-bidi from
 * "plaintext" (auto-detect per paragraph) to "normal" (respect dir attribute).
 * This ensures cursor position, text alignment, and heading layout follow
 * the user's explicit LTR/RTL setting.
 */
.ProseMirror[dir="ltr"] p,
.ProseMirror[dir="ltr"] h1,
.ProseMirror[dir="ltr"] h2,
.ProseMirror[dir="ltr"] h3,
.ProseMirror[dir="ltr"] h4,
.ProseMirror[dir="ltr"] h5,
.ProseMirror[dir="ltr"] h6,
.ProseMirror[dir="ltr"] li,
.ProseMirror[dir="ltr"] li p,
.ProseMirror[dir="ltr"] blockquote,
.ProseMirror[dir="ltr"] td,
.ProseMirror[dir="ltr"] th,
.ProseMirror[dir="ltr"] .details-content p,
.ProseMirror[dir="ltr"] [data-type="detailsContent"] p,
.ProseMirror[dir="rtl"] p,
.ProseMirror[dir="rtl"] h1,
.ProseMirror[dir="rtl"] h2,
.ProseMirror[dir="rtl"] h3,
.ProseMirror[dir="rtl"] h4,
.ProseMirror[dir="rtl"] h5,
.ProseMirror[dir="rtl"] h6,
.ProseMirror[dir="rtl"] li,
.ProseMirror[dir="rtl"] li p,
.ProseMirror[dir="rtl"] blockquote,
.ProseMirror[dir="rtl"] td,
.ProseMirror[dir="rtl"] th,
.ProseMirror[dir="rtl"] .details-content p,
.ProseMirror[dir="rtl"] [data-type="detailsContent"] p {
    unicode-bidi: normal;
}

.ProseMirror hr {
    border: none;
    height: 1px;
    background-color: var(--border-color);
    opacity: 0.6;
    /* Softer than standard borders */
    margin: var(--editor-paragraph-spacing) 0;
}

.ProseMirror a {
    color: var(--accent-color);
    text-decoration: underline;
    cursor: pointer;
}

.ProseMirror mark {
    border-radius: 2px;
    padding: 0 2px;
}

.ProseMirror p.is-editor-empty:first-child::before,
.ProseMirror h1.is-editor-empty:first-child::before,
.ProseMirror h2.is-editor-empty:first-child::before,
.ProseMirror h3.is-editor-empty:first-child::before,
.ProseMirror h4.is-editor-empty:first-child::before,
.ProseMirror h5.is-editor-empty:first-child::before,
.ProseMirror h6.is-editor-empty:first-child::before {
    content: attr(data-placeholder);
    color: var(--placeholder-color);
    pointer-events: none;
    float: inline-start;
    height: 0;
}

.ProseMirror-focused {
    outline: none;
}

/* Block Selection Gutter - invisible area to allow block selection */
.block-selection-gutter {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    width: 14px;
    z-index: 1;
}

/* For tables, the gutter should be relative to the wrapper */
.tableWrapper {
    position: relative;
    margin: var(--editor-paragraph-spacing) 0;
}

/* Selected Node Highlights */
.ProseMirror-selectednode {
    outline: 2px solid var(--accent-color, #007AFF) !important;
    outline-offset: -2px;
}

/* Overlay for rich nodes to show they are selected as a block */
.flashcard-block.ProseMirror-selectednode::after,
.tableWrapper.ProseMirror-selectednode::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 122, 255, 0.08);
    pointer-events: none;
    z-index: 5;
    border-radius: inherit;
}

/* ─── Drag Handle (desktop only) ─────────────────────────────────────────── */

/*
 * Add left padding only on pointer/hover-capable devices (desktop).
 * This ensures mobile WebView editors are never affected.
 */
@media (hover: hover) and (pointer: fine) {
    .ProseMirror {
        padding-left: 36px;
    }

    .ProseMirror[dir="rtl"] {
        padding-left: 16px;
        padding-right: 36px;
    }
}

/* The floating handle element rendered by DragHandle.configure({ render }) */
.annota-drag-handle {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 24px;
    border-radius: 4px;
    /* Visible by default with accent tint so it's easy to spot */
    color: color-mix(in srgb, var(--accent-color) 60%, var(--text-color));
    opacity: 0;
    cursor: grab;
    transition: opacity 0.12s ease, color 0.12s ease, background-color 0.12s ease;
    transform: translate(-4px, 2px);
    user-select: none;
    -webkit-user-select: none;
    /* Must sit above code-block stacking contexts (z-index: 2) */
    z-index: 10;
    position: absolute;
}

.annota-drag-handle.rtl {
    transform: translate(4px, 2px);
}



.annota-drag-handle svg {
    display: block;
    flex-shrink: 0;
    pointer-events: none;
}

/* The plugin shows the handle by clearing visibility; hidden = opacity 0 */
.annota-drag-handle:not([style*="visibility: hidden"]) {
    opacity: 0.65;
}

.annota-drag-handle:hover {
    opacity: 1 !important;
    color: var(--accent-color);
    background-color: color-mix(in srgb, var(--accent-color) 12%, transparent);
}

.annota-drag-handle:active {
    cursor: grabbing;
    opacity: 1 !important;
    color: var(--accent-color);
    background-color: color-mix(in srgb, var(--accent-color) 50%, transparent);
}

/* Subtle highlight on the block currently under the drag handle */
.drag-handle-hover {
    border-radius: 4px;
    outline: none;
}

/* Show the outline ONLY when hovering the actual drag handle */
:has(.annota-drag-handle:hover) .drag-handle-hover {
    outline: 1.5px solid color-mix(in srgb, var(--accent-color) 35%, transparent);
    outline-offset: 2px;
}

/* Don't double-highlight blocks that are already selected */
:has(.annota-drag-handle:hover) .drag-handle-hover.ProseMirror-selectednode {
    outline: none;
}

/* Source: src/styles/highlight-theme.css */
/* 
 * Custom Highlight.js theme supporting Light and Dark modes.
 * Based on Atom One Light and Atom One Dark themes.
 */

:root {
    /* Atom One Light */
    --hljs-bg: #fafafa;
    --hljs-color: #383a42;
    --hljs-comment: #a0a1a7;
    --hljs-keyword: #a626a4;
    --hljs-section: #e45649;
    --hljs-literal: #0184bb;
    --hljs-string: #50a14f;
    --hljs-attr: #986801;
    --hljs-symbol: #4078f2;
    --hljs-built_in: #c18401;
}

/* Fallback for system dark mode */
@media (prefers-color-scheme: dark) {
    :root {
        --hljs-bg: #282c34;
        --hljs-color: #abb2bf;
        --hljs-comment: #5c6370;
        --hljs-keyword: #c678dd;
        --hljs-section: #e06c75;
        --hljs-literal: #56b6c2;
        --hljs-string: #98c379;
        --hljs-attr: #d19a66;
        --hljs-symbol: #61aeee;
        --hljs-built_in: #e6c07b;
    }
}

/* Explicit dark mode class (used by Tailwind and our theme hook) */
.dark {
    --hljs-bg: #282c34;
    --hljs-color: #abb2bf;
    --hljs-comment: #5c6370;
    --hljs-keyword: #c678dd;
    --hljs-section: #e06c75;
    --hljs-literal: #56b6c2;
    --hljs-string: #98c379;
    --hljs-attr: #d19a66;
    --hljs-symbol: #61aeee;
    --hljs-built_in: #e6c07b;
}

pre code.hljs {
    display: block;
    overflow-x: auto;
    padding: 1em;
}

code.hljs {
    padding: 3px 5px;
}

.hljs {
    color: var(--hljs-color);
    background: var(--hljs-bg);
}

.hljs-comment,
.hljs-quote {
    color: var(--hljs-comment);
    font-style: italic;
}

.hljs-doctag,
.hljs-keyword,
.hljs-formula {
    color: var(--hljs-keyword);
}

.hljs-section,
.hljs-name,
.hljs-selector-tag,
.hljs-deletion,
.hljs-subst {
    color: var(--hljs-section);
}

.hljs-literal {
    color: var(--hljs-literal);
}

.hljs-string,
.hljs-regexp,
.hljs-addition,
.hljs-attribute,
.hljs-meta .hljs-string {
    color: var(--hljs-string);
}

.hljs-attr,
.hljs-variable,
.hljs-template-variable,
.hljs-type,
.hljs-selector-class,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-number {
    color: var(--hljs-attr);
}

.hljs-symbol,
.hljs-bullet,
.hljs-link,
.hljs-meta,
.hljs-selector-id,
.hljs-title {
    color: var(--hljs-symbol);
}

.hljs-built_in,
.hljs-title.class_,
.hljs-class .hljs-title {
    color: var(--hljs-built_in);
}

.hljs-emphasis {
    font-style: italic;
}

.hljs-strong {
    font-weight: bold;
}

.hljs-link {
    text-decoration: underline;
}

/* Source: src/extensions/code-block.css */
/* Style only inline code (not inside a pre) */
.ProseMirror :not(pre)>code {
    color: color-mix(in srgb, var(--text-color), var(--accent-full) 75%);
    background-color: color-mix(in srgb, var(--code-bg), var(--accent) 25%);
    padding: 2px 6px;
    border-radius: 4px;
    font-family: 'FiraCode', 'SF Mono', Monaco, Consolas, 'Courier New', monospace;
    font-size: calc(var(--editor-font-size) * 0.85);
}

.ProseMirror pre {
    padding: 12px 12px 12px 12px;
    border-radius: 8px;
    overflow-x: auto;
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
    font-family: 'FiraCode', 'SF Mono', Monaco, Consolas, 'Courier New', monospace;
    font-size: calc(var(--editor-font-size) * 0.875);
    line-height: 1.7;
    position: relative;
    direction: ltr !important;
    unicode-bidi: isolate !important;
    white-space: pre !important;
    word-break: normal !important;
    overflow-wrap: normal !important;
}

.ProseMirror pre code {
    background: none !important;
    padding: 0 !important;
    margin: 0 !important;
    font-size: inherit;
    font-family: inherit;
    display: inline !important;
}

/* Code block wrapper with header — uses CSS grid for gutter + pre layout */
.code-block-wrapper {
    position: relative;
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
    direction: ltr !important;
    unicode-bidi: isolate !important;
    background-color: var(--code-block-bg);
    border-radius: 8px;
    display: grid;
    grid-template-columns: auto 1fr;
}

.code-block-wrapper.no-line-numbers {
    grid-template-columns: 1fr;
}

.code-block-wrapper pre {
    margin: 0;
    min-width: 0;
}

/* Header bar for code block */
.code-block-header {
    grid-column: 1 / -1;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 8px;
    background-color: transparent;
    top: 0;
    left: 0;
    right: 0;
    /* z-index raised here creates a stacking context — the drag handle wrapper
       sits outside this element and must be higher to appear above the header */
    z-index: 2;
    pointer-events: none;
}

/* Language selector button (LEFT) */
.code-lang-select {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 2px 6px;
    border-radius: 4px;
    background: color-mix(in srgb, var(--text-color) 15%, transparent);
    border: none;
    font-family: 'FiraCode', 'SF Mono', Monaco, Consolas, monospace;
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-color);
    cursor: pointer;
    transition: all 0.15s ease;
    user-select: none;
    opacity: 0.5;
    pointer-events: auto;
}

.code-lang-select:hover {
    opacity: 0.8;
}

/* Menu button (RIGHT) */
.code-menu-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 20px;
    border-radius: 4px;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    user-select: none;
    opacity: 0.25;
    pointer-events: auto;
}

.code-menu-btn:hover {
    opacity: 0.7;
}

.code-menu-btn svg {
    width: 20px;
    height: 20px;
    flex-shrink: 0;
}

/* Line number gutter — sits in grid column 1, pre sits in column 2 */
.code-gutter {
    display: flex;
    flex-direction: column;
    align-self: stretch;
    user-select: none;
    text-align: right;
    color: color-mix(in srgb, var(--text-color) 30%, transparent);
    padding: 12px 4px 12px 12px;
    /* min-width: 36px; */
    box-sizing: border-box;
    pointer-events: none;
    flex-shrink: 0;
    font-family: 'FiraCode', 'SF Mono', Monaco, Consolas, 'Courier New', monospace;
    font-size: calc(var(--editor-font-size) * 0.875);
    line-height: 1.7;
}

.code-gutter span {
    display: block;
    box-sizing: border-box;
    color: inherit;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}

/* ========================================
   Print Mode Overrides
   ======================================= */

/* Style static code blocks in print mode where .code-block-wrapper is absent */
.ProseMirror.print-mode pre {
    background-color: var(--code-block-bg) !important;
    border: 1px solid var(--border-color) !important;
    padding: 16px !important;
    border-radius: 8px !important;
    color: var(--text-color) !important;
    white-space: pre-wrap !important;
    word-break: break-all !important;
    overflow-wrap: anywhere !important;
}

.ProseMirror.print-mode pre code {
    white-space: pre-wrap !important;
    word-break: break-all !important;
    background: none !important;
    padding: 0 !important;
}

/* Style code block wrapper and gutter in print mode if line numbers are enabled */
.ProseMirror.print-mode .code-block-wrapper {
    border: 1px solid var(--border-color) !important;
    background-color: var(--code-block-bg) !important;
    margin-bottom: var(--editor-paragraph-spacing) !important;
}

/* Reset individual pre styling inside the wrapper to prevent duplication */
.ProseMirror.print-mode .code-block-wrapper pre {
    background: none !important;
    border: none !important;
    padding: 12px 12px 12px 0 !important;
    /* Left padding is handled by the gutter */
    margin: 0 !important;
    border-radius: 0 !important;
}

.ProseMirror.print-mode .code-block-wrapper .code-gutter {
    padding: 12px 8px 12px 12px !important;
    margin-right: 8px !important;
}

/* Source: src/extensions/custom-youtube.css */
/* YouTube NodeView wrapper — the host element rendered by addNodeView */
.yt-wrapper {
    display: flex;
    justify-content: center;
    width: 100%;
    margin: calc(var(--editor-paragraph-spacing) * 2) 0;
}

/* The clickable anchor that wraps the thumbnail */
.yt-embed-link {
    display: block;
    /* ← not flex */
    position: relative;
    width: 100%;
    padding-bottom: 56.25%;
    height: 0;
    overflow: hidden;
    border-radius: 12px;
    background: #000;
    box-shadow: 0 10px 30px -10px rgba(0, 0, 0, 0.5);
    isolation: isolate;
    cursor: pointer;
}

.yt-thumbnail {
    position: absolute;
    top: 0;
    left: 0;

    /* Force override ProseMirror defaults */
    width: 100% !important;
    height: 100% !important;
    max-width: none !important;
    /* This is usually the main culprit */
    min-width: 100% !important;
    min-height: 100% !important;
    margin: 0 !important;
    display: block !important;

    object-fit: cover;
    object-position: center;
    opacity: 0.9;
    transition: transform 0.6s cubic-bezier(0.2, 0, 0.2, 1), opacity 0.3s ease;
}

.yt-embed-link:hover .yt-thumbnail {
    opacity: 1;
    transform: scale(1.05);
    /* Clean scale up */
}

/* Play button overlay */
.yt-play-button {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 68px;
    height: 68px;
    background: rgba(255, 255, 255, 0.15);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    border: 1px solid rgba(255, 255, 255, 0.4);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
    transition: all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
    z-index: 2;
}

/* Triangle play icon */
.yt-play-icon {
    width: 0;
    height: 0;
    border-top: 14px solid transparent;
    border-bottom: 14px solid transparent;
    border-left: 24px solid white;
    margin-left: 8px;
}

/* Hover effects */
.yt-embed-link:hover .yt-play-button {
    transform: translate(-50%, -50%) scale(1.15);
    background: rgba(255, 255, 255, 0.25);
    border-color: rgba(255, 255, 255, 0.6);
}

/* Legacy iframe styles (for old iframe embeds) */
.ProseMirror div[data-youtube-video] {
    margin: var(--editor-paragraph-spacing) 0;
    width: 100%;
    display: flex;
    justify-content: center;
}

.ProseMirror iframe {
    width: 100% !important;
    height: auto !important;
    aspect-ratio: 16 / 9;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

/* Error state */
.youtube-error {
    padding: 20px;
    background: rgba(255, 0, 0, 0.05);
    border: 1px solid rgba(255, 0, 0, 0.2);
    border-radius: 8px;
    color: #ef4444;
    font-size: 14px;
    text-align: center;
    width: 100%;
    max-width: 640px;
}

/* Source: src/extensions/details.css */
/* ========================================
   Details / Collapsible Section Styles
   Modern, clean design matching React Native
   ======================================== */

/* Main wrapper */
.ProseMirror .details-wrapper,
.ProseMirror [data-type="details"] {
    margin: 0;
    margin-bottom: calc(var(--editor-paragraph-spacing));
    margin-top: calc(var(--editor-paragraph-spacing));
    border-radius: 8px;
    border: 1px solid color-mix(in srgb, var(--border-color), transparent 50%);
    overflow: hidden;
    background-color: transparent;
    transition: background-color 0.2s ease;
}

/* Visualization for where the drop will land */
.ProseMirror .details-wrapper,
.ProseMirror [data-type="details"] {
    -webkit-user-drag: none;
}

/* Summary/Header - editable title with arrow toggle */
.ProseMirror .details-summary,
.ProseMirror [data-type="detailsSummary"] {
    display: flex !important;
    align-items: center !important;
    padding: 10px 8px !important;
    padding-inline-start: 4px !important;

    gap: 0px !important;
    transition: background-color 0.15s ease;
    min-height: 32px !important;
}

/* Summary Content alignment and placeholder */
.details-summary-content {
    position: relative;
    outline: none;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.ProseMirror .details-summary-content>*,
.ProseMirror [data-type="detailsSummary"] .details-summary-content>*,
.ProseMirror .details-summary-content h1,
.ProseMirror .details-summary-content h2,
.ProseMirror .details-summary-content h3,
.ProseMirror .details-summary-content h4,
.ProseMirror .details-summary-content p {
    margin: 0 !important;
    padding: 0 !important;
    border: none !important;
    min-height: 0 !important;
    line-height: 1.4 !important;
    height: auto !important;
}

.details-menu-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 24px;
    height: 24px;
    border-radius: 4px;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    opacity: 0.25;
    margin-inline-end: 8px;
}

.details-menu-btn:hover {
    opacity: 0.7;
}

@media (max-width: 768px) {
    .details-menu-btn {
        width: 32px;
        height: 32px;
    }
}

/* Arrow indicator - clickable toggle button on the left */
.details-toggle {
    width: 32px;
    align-self: stretch;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    flex-shrink: 0;
    user-select: none;
}

/* Arrow rotates when open */
.details-arrow {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    transition: transform 0.2s ease;
}

/* RTL closed state: point left (180deg) */
.ProseMirror[dir="rtl"] .details-arrow {
    transform: rotate(180deg);
}

/* Open state: both LTR and RTL point down (90deg) */
.ProseMirror [data-type="details"][data-open="true"] .details-arrow {
    transform: rotate(90deg);
}

.details-arrow svg {
    opacity: 0.7;
    width: 16px;
    height: 16px;
    display: block;
    transform-origin: center;
}

/* Content area - below the header */
.ProseMirror .details-content,
.ProseMirror [data-type="detailsContent"] {
    padding-block: calc(var(--editor-paragraph-spacing) / 2);
    padding-inline-start: 36px;
    padding-inline-end: 14px;
    overflow: hidden;
    transition: height 0.25s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.25s cubic-bezier(0.4, 0, 0.2, 1);
}

/* Hide content when collapsed - using height and opacity instead of display: none for animation */
.ProseMirror [data-type="details"]:not([data-open="true"]):not([open]) .details-content,
.ProseMirror [data-type="details"]:not([data-open="true"]):not([open]) [data-type="detailsContent"] {
    height: 0;
    padding-top: 0;
    padding-bottom: 0;
    opacity: 0;
    pointer-events: none;
}


/* Remove default margins in content */
.ProseMirror .details-content>*:first-child,
.ProseMirror [data-type="detailsContent"]>*:first-child {
    margin-top: 0;
}

.ProseMirror .details-content>*:last-child,
.ProseMirror [data-type="detailsContent"]>*:last-child {
    margin-bottom: 0;
}

/* Selected state */
.ProseMirror [data-type="details"].ProseMirror-selectednode {
    outline: 2px solid var(--accent-color);
    outline-offset: -2px;
}

/* ========================================
   Print Mode Overrides
   ======================================== */

/* Keep collapsible details expanded in PDF print output */
.ProseMirror.print-mode [data-type="details"] .details-content,
.ProseMirror.print-mode [data-type="details"] [data-type="detailsContent"] {
    height: auto !important;
    opacity: 1 !important;
    padding-top: calc(var(--editor-paragraph-spacing) / 2) !important;
    padding-bottom: calc(var(--editor-paragraph-spacing) / 2) !important;
    pointer-events: auto !important;
}

/* Hide interactive toggle controls in PDF exports */
.ProseMirror.print-mode .details-toggle,
.ProseMirror.print-mode .details-menu-btn {
    display: none !important;
}

/* Source: src/extensions/file-attachment.css */
.file-attachment-menu-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: 4px;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    opacity: 0.2;
    transition: all 0.2s ease;
    margin-inline-start: 4px;
}

.file-attachment-card:hover .file-attachment-menu-btn {
    opacity: 1;
}

.file-attachment-menu-btn:hover {
    background-color: rgba(128, 128, 128, 0.1);
}

.file-attachment-wrapper {
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
    position: relative;
}

.file-attachment-card {
    display: flex;
    align-items: center;
    padding: 12px;
    background-color: var(--code-block-bg, #2A2A2A);
    border-radius: 8px;
    cursor: pointer;
    border: 1px solid var(--border-color, rgba(255, 255, 255, 0.1));
    transition: background-color 0.2s, border-color 0.2s;
}

.file-attachment-card:hover {
    background-color: var(--quote-bg, rgba(255, 255, 255, 0.15));
    border-color: var(--accent-color, #3b82f6);
}

.file-attachment-icon {
    margin-inline-end: 12px;
    font-size: 24px;
    flex-shrink: 0;
}

.file-attachment-info {
    display: flex;
    flex-direction: column;
    overflow: hidden;
    flex: 1;
}

.file-attachment-name {
    color: var(--text-color, #FFFFFF);
    font-weight: 600;
    font-size: 14px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.file-attachment-size {
    color: var(--placeholder-color, rgba(255, 255, 255, 0.5));
    font-size: 12px;
    margin-top: 2px;
}


/* Source: src/extensions/flashcard.css */
/* ========================================
   Flashcard Block
   ======================================== */

.flashcard-block {
    margin: var(--editor-paragraph-spacing) 0;
    border: 1.5px solid var(--border-color);
    border-radius: 8px;
    background: var(--bg-color);
    overflow: hidden;
    position: relative;
    user-select: none;
}



/* --- Header --- */
.flashcard-header {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 10px 8px 10px 14px;
    border-bottom: 1px solid color-mix(in srgb, var(--border-color), transparent 60%);
}

.flashcard-title-input {
    flex: 1;
    min-width: 0;
    background: transparent;
    border: none;
    outline: none;
    font-size: 15px;
    font-weight: 600;
    color: var(--text-color);
    font-family: inherit;
    padding: 0;
}

.flashcard-title-input::placeholder {
    color: var(--placeholder-color);
    opacity: 0.6;
}

.flashcard-header-right {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-shrink: 0;
}

.flashcard-counter {
    font-size: 11px;
    font-weight: 700;
    color: var(--text-color);
    opacity: 0.6;
    user-select: none;
    white-space: nowrap;
    min-width: 36px;
    text-align: center;
    letter-spacing: 0.05em;
}

/* Action buttons */
.flashcard-action-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    border-radius: 6px;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    opacity: 0.5;
    transition: all 0.15s ease;
}

.flashcard-action-btn:hover {
    background: color-mix(in srgb, var(--border-color), transparent 50%);
    opacity: 1 !important;
}

.flashcard-action-btn.active {
    opacity: 1 !important;
    color: var(--accent-full, var(--accent-color));
    background: color-mix(in srgb, var(--accent-color), transparent 80%);
}

/* --- Card Area --- */
.flashcard-card-area {
    position: relative;
    min-height: 200px;
    display: flex;
    flex-direction: column;
}

.flashcard-footer-nav {
    position: absolute;
    bottom: 12px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    align-items: center;
    gap: 8px;
    z-index: 15;
    background: color-mix(in srgb, var(--bg-color, #fff), transparent 20%);
    backdrop-filter: blur(8px);
    -webkit-backdrop-filter: blur(8px);
    padding: 4px 8px;
    border-radius: 20px;
    border: 1px solid color-mix(in srgb, var(--border-color), transparent 80%);
    transition: all 0.2s ease;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.flashcard-nav-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 24px;
    height: 24px;
    border-radius: 50%;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    opacity: 0.5;
    transition: all 0.15s ease;
    padding: 0;
}

.flashcard-nav-btn:hover {
    background: color-mix(in srgb, var(--border-color), transparent 50%);
    opacity: 1;
}

.flashcard-nav-btn svg {
    width: 16px;
    height: 16px;
}

.flashcard-card-container {
    padding: 0;
    cursor: pointer;
    height: 200px;
    display: flex;
    flex-direction: column;
    position: relative;
}


/* Slide Animations */
@keyframes flashcardSlideInRight {
    from {
        transform: translateX(14px);
        opacity: 0.72;
    }

    to {
        transform: translateX(0);
        opacity: 1;
    }
}

@keyframes flashcardSlideInLeft {
    from {
        transform: translateX(-14px);
        opacity: 0.72;
    }

    to {
        transform: translateX(0);
        opacity: 1;
    }
}

.slide-in-right .flashcard-card-inner {
    animation: flashcardSlideInRight 0.22s cubic-bezier(0.22, 0.8, 0.24, 1);
}

.slide-in-left .flashcard-card-inner {
    animation: flashcardSlideInLeft 0.22s cubic-bezier(0.22, 0.8, 0.24, 1);
}

.flashcard-card-inner {
    position: relative;
    width: 100%;
    height: 100%;
}

.flashcard-card-inner.no-transition .flashcard-card-face {
    transition: none !important;
}

.flashcard-card-inner.is-flipped .flashcard-card-front {
    opacity: 0;
    transform: translateY(-4px);
    pointer-events: none;
    z-index: 1;
}

.flashcard-card-inner.is-flipped .flashcard-card-back {
    opacity: 1;
    transform: translateY(0);
    pointer-events: auto;
    z-index: 2;
}

.flashcard-card-face {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    transition: opacity 0.18s ease, transform 0.18s ease;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    padding: 12px 20px 16px;
    font-size: 18px;
    line-height: 1.5;
    color: var(--text-color);
    user-select: none;
    box-sizing: border-box;
    overflow: hidden;
    justify-content: flex-start;
}

@media (max-width: 600px) {
    .flashcard-card-face {
        font-size: 15px;
    }
}

.flashcard-side-label {
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--accent-full, var(--accent-color));
    opacity: 0.7;
    user-select: none;
    pointer-events: none;
    margin-bottom: 12px;
    flex-shrink: 0;
}

.flashcard-card-text {
    width: 100%;
    white-space: pre-wrap;
    word-break: break-word;
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow-y: auto;
}

.flashcard-card-front {
    background: var(--bg-color, #fff);
    font-weight: 500;
    opacity: 1;
    transform: translateY(0);
    z-index: 2;
}

.flashcard-card-back {
    background: var(--bg-color, #fff);
    opacity: 0;
    transform: translateY(4px);
    pointer-events: none;
    z-index: 1;
}

.flashcard-card-face.empty {
    opacity: 0.4;
    font-style: italic;
}

/* Navigation Overlays */
.flashcard-nav-overlay-btn {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    z-index: 10;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: 50%;
    background: color-mix(in srgb, var(--bg-color, #fff), transparent 30%);
    backdrop-filter: blur(4px);
    -webkit-backdrop-filter: blur(4px);
    border: 1px solid color-mix(in srgb, var(--border-color), transparent 60%);
    color: var(--text-color);
    cursor: pointer;
    opacity: 0;
    transition: all 0.2s ease;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.flashcard-block:hover .flashcard-nav-overlay-btn {
    opacity: 0.6;
}

.flashcard-nav-overlay-btn:hover {
    opacity: 1 !important;
    background: var(--bg-color, #fff);
    border-color: var(--accent-color);
    color: var(--accent-color);
}

.flashcard-prev-btn {
    left: 8px;
}

.flashcard-next-btn {
    right: 8px;
}

/* --- Edit Pane --- */
.flashcard-edit-pane {
    padding: 12px 12px 48px 12px;
    /* Extra bottom padding for footer nav */
    display: flex;
    flex-direction: column;
    gap: 12px;
    background: color-mix(in srgb, var(--border-color), transparent 95%);
    border-top: 1px solid var(--border-color);
    box-sizing: border-box;
    width: 100%;
}

.flashcard-edit-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 4px;
}

.flashcard-edit-header span {
    font-size: 12px;
    font-weight: 600;
    opacity: 0.6;
}

.flashcard-order-controls {
    display: flex;
    gap: 4px;
}

.flashcard-order-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 24px;
    height: 24px;
    border-radius: 4px;
    border: 1px solid var(--border-color);
    background: transparent;
    color: var(--text-color);
    cursor: pointer;
    transition: all 0.2s;
}

.flashcard-order-btn:hover:not(:disabled) {
    background: var(--border-color);
}

.flashcard-order-btn:disabled {
    opacity: 0.3;
    cursor: not-allowed;
}

.flashcard-edit-label {
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--accent-full, var(--accent-color));
    opacity: 0.6;
    user-select: none;
    margin-bottom: -4px;
}

.flashcard-edit-input {
    width: 100%;
    padding: 10px 12px;
    border-radius: 10px;
    border: 1px solid color-mix(in srgb, var(--border-color), transparent 50%);
    background: var(--bg-color, #fff);
    color: var(--text-color);
    font-size: 14px;
    font-family: inherit;
    resize: vertical;
    outline: none;
    transition: all 0.15s ease;
    box-sizing: border-box;
    min-height: 80px;
}

.flashcard-edit-input:focus {
    border-color: var(--accent-color);
    box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent-color), transparent 90%);
}

.flashcard-edit-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 8px;
    padding-top: 12px;
    border-top: 1px solid var(--border-color);
    min-height: 32px;
}

.flashcard-edit-footer-right {
    display: flex;
    gap: 8px;
}

.flashcard-edit-btn-small {
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 4px 10px;
    height: 28px;
    border-radius: 6px;
    font-size: 12px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
    border: 1px solid var(--border-color);
    background: var(--bg-color);
    color: var(--text-color);
    white-space: nowrap;
    flex-shrink: 0;
    box-sizing: border-box;
}

.flashcard-edit-btn-small:hover {
    background: color-mix(in srgb, var(--border-color), transparent 80%);
}

.flashcard-edit-btn-small svg {
    opacity: 0.7;
}

.flashcard-delete-btn {
    color: #ef4444;
    border-color: color-mix(in srgb, #ef4444, transparent 80%);
}

.flashcard-delete-btn:hover {
    background: color-mix(in srgb, #ef4444, transparent 90%);
}

.flashcard-done-btn {
    background: var(--accent-full, var(--accent-color));
    color: #fff;
    border-color: var(--accent-full, var(--accent-color));
}

.flashcard-done-btn:hover {
    opacity: 0.9;
}

.flashcard-done-btn svg {
    opacity: 1;
}

/* Three-dot menu */
.flashcard-menu-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    border-radius: 6px;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    opacity: 0.25;
}

.flashcard-menu-btn:hover {
    opacity: 0.7 !important;
}

/* Selected state */
.flashcard-block.ProseMirror-selectednode {
    outline: 2px solid var(--accent-color);
    outline-offset: -2px;
}

/* Mobile: always show action buttons */
@media (max-width: 768px) {
    .flashcard-nav-overlay-btn {
        opacity: 0.7;
        width: 40px;
        height: 40px;
    }

    .flashcard-card-container {
        padding: 10px 35px;
    }
}

/* Source: src/extensions/heading.css */
.ProseMirror h1 {
    font-size: calc(var(--editor-font-size) * 2);
    font-weight: 700;
    margin: calc(var(--editor-paragraph-spacing) * 1.5) 0 calc(var(--editor-paragraph-spacing) * 0.8) 0;
    line-height: calc(1.1 + (var(--editor-line-height) - 1.5) * 0.5);
    unicode-bidi: plaintext;
    text-align: start;
}

.ProseMirror h2 {
    font-size: calc(var(--editor-font-size) * 1.625);
    font-weight: 600;
    margin: calc(var(--editor-paragraph-spacing) * 1.25) 0 calc(var(--editor-paragraph-spacing) * 0.6) 0;
    line-height: calc(1.2 + (var(--editor-line-height) - 1.5) * 0.5);
    unicode-bidi: plaintext;
    text-align: start;
}

.ProseMirror h3 {
    font-size: calc(var(--editor-font-size) * 1.375);
    font-weight: 500;
    margin: var(--editor-paragraph-spacing) 0 calc(var(--editor-paragraph-spacing) * 0.5) 0;
    line-height: calc(1.2 + (var(--editor-line-height) - 1.5) * 0.5);
    unicode-bidi: plaintext;
    text-align: start;
}

.ProseMirror h4 {
    font-size: calc(var(--editor-font-size) * 1.125);
    font-weight: 500;
    margin: calc(var(--editor-paragraph-spacing) * 0.8) 0 calc(var(--editor-paragraph-spacing) * 0.4) 0;
    line-height: calc(1.3 + (var(--editor-line-height) - 1.5) * 0.5);
    unicode-bidi: plaintext;
    text-align: start;
}

.ProseMirror h5 {
    font-size: var(--editor-font-size);
    font-weight: 600;
    margin: calc(var(--editor-paragraph-spacing) * 0.6) 0 calc(var(--editor-paragraph-spacing) * 0.3) 0;
    line-height: 1.4;
    unicode-bidi: plaintext;
    text-align: start;
}

.ProseMirror h6 {
    font-size: calc(var(--editor-font-size) * 0.875);
    font-weight: 600;
    margin: calc(var(--editor-paragraph-spacing) * 0.5) 0 calc(var(--editor-paragraph-spacing) * 0.2) 0;
    line-height: 1.4;
    unicode-bidi: plaintext;
    text-align: start;
}


/* Source: src/extensions/image.css */
.ProseMirror img {
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    display: block;
    width: auto;
}

/* Image node wrapper */
.image-node-wrapper {
    position: relative;
    display: block;
    /* Changed from inline-block */
    max-width: 100%;
    margin: 8px 0;
    width: fit-content;
    line-height: 0;
}

.image-node-wrapper img {
    width: 100% !important;
    height: auto !important;
    display: block;
}

.image-node-wrapper.ProseMirror-selectednode {
    outline: 3px solid var(--accent-color);
    border-radius: 8px;
}

.image-node-wrapper.img-center {
    margin: 8px auto;
}

.image-node-wrapper.img-left {
    margin: 8px auto 8px 0;
}

.image-node-wrapper.img-right {
    margin: 8px 0 8px auto;
}

/* Three-dot menu button on images */
.image-menu-btn {
    position: absolute;
    display: none;
    top: 8px;
    right: 8px;
    width: 28px;
    height: 28px;
    border-radius: 14px;
    background: rgba(0, 0, 0, 0.45);
    border: none;
    color: #fff;
    cursor: pointer;
    z-index: 5;
    align-items: center;
    justify-content: center;
    padding: 0;
    opacity: 0.6;
    transition: opacity 0.15s ease;
    user-select: none;
    -webkit-user-select: none;
    touch-action: manipulation;
}

.image-node-wrapper:hover .image-menu-btn,
.image-node-wrapper.ProseMirror-selectednode .image-menu-btn {
    display: flex !important;
}

.image-menu-btn:hover,
.image-menu-btn:active {
    opacity: 1;
    background: rgba(0, 0, 0, 0.65);
}

.image-menu-btn svg {
    flex-shrink: 0;
}

body.is-resizing-image {
    cursor: nwse-resize !important;
    user-select: none !important;
    -webkit-user-select: none !important;
}

/* Resize handle */
.image-resize-handle {
    position: absolute;
    bottom: 6px;
    right: 6px;
    width: 22px;
    height: 22px;
    color: #fff;
    cursor: nwse-resize;
    z-index: 10;
    opacity: 0;
    transition: opacity 0.2s ease, transform 0.2s ease;
    touch-action: none;
    display: flex;
    align-items: center;
    justify-content: center;
}

.image-resize-handle:hover {
    background-color: color-mix(in srgb, var(--accent-color), transparent 40%);
    border-radius: 50%;
}

.image-node-wrapper:hover .image-resize-handle,
.image-node-wrapper.ProseMirror-selectednode .image-resize-handle {
    opacity: 1;
}

.image-resize-handle:hover {
    transform: scale(1.2);
}

.image-resize-handle::after {
    content: '';
    position: absolute;
    top: -10px;
    left: -10px;
    right: -10px;
    bottom: -10px;
}

/* Source: src/extensions/marks.css */
.tc-yw { color: #FFE066; }
.tc-or { color: #FFA94D; }
.tc-re { color: #FF6B6B; }
.tc-pi { color: #F783AC; }
.tc-in { color: #818CF8; }
.tc-bl { color: #74C0FC; }
.tc-te { color: #20C997; }
.tc-gr { color: #51CF66; }
.tc-gy { color: #757575; }
.tc-br { color: #A07855; }

.hl-yw { background-color: rgba(255, 224, 102, 0.3); color: inherit; }
.hl-or { background-color: rgba(255, 169, 77, 0.3); color: inherit; }
.hl-re { background-color: rgba(255, 107, 107, 0.3); color: inherit; }
.hl-pi { background-color: rgba(247, 131, 172, 0.3); color: inherit; }
.hl-in { background-color: rgba(129, 140, 248, 0.3); color: inherit; }
.hl-bl { background-color: rgba(116, 192, 252, 0.3); color: inherit; }
.hl-te { background-color: rgba(32, 201, 151, 0.3); color: inherit; }
.hl-gr { background-color: rgba(81, 207, 102, 0.3); color: inherit; }
.hl-gy { background-color: rgba(114, 114, 114, 0.3); color: inherit; }
.hl-br { background-color: rgba(160, 120, 85, 0.3); color: inherit; }


/* Source: src/extensions/math.css */
/* Math / KaTeX Styles */
/* Tiptap mathematics uses data-type="inline-math"/"block-math" + .tiptap-mathematics-render */
[data-type="math"],
[data-type="inlineMath"],
[data-type="inline-math"],
.tiptap-mathematics-render[data-type="inline-math"],
.math-node {
    display: inline-block;
    contain: paint;
    align-items: center;
    position: relative;
    vertical-align: middle;
    padding: 0;
    margin: 0 3px;
    border-radius: 4px;
    cursor: pointer !important;
    line-height: 1;
    pointer-events: auto;
    white-space: nowrap;
    max-width: 100%;
    direction: ltr !important;
    -webkit-user-select: text !important;
    user-select: text !important;
}


[data-type*="math"]::selection,
[data-type*="math"] *::selection {
    background-color: transparent !important;
    color: inherit !important;
}

/* Firefox support */
[data-type*="math"]::-moz-selection,
[data-type*="math"] *::-moz-selection {
    background-color: transparent !important;
    color: inherit !important;
}

[data-type="math"] .katex,
[data-type="inlineMath"] .katex,
[data-type="inline-math"] .katex,
[data-type="blockMath"] .katex,
[data-type="block-math"] .katex,
.tiptap-mathematics-render .katex,
.math-node .katex {
    display: inline-block;
    align-items: center;
    border-radius: 4px;
    max-width: 100%;
    line-height: 1;
    font-size: clamp(0.7em, 3cqw, 1.1em);
    -webkit-user-select: text !important;
    user-select: text !important;
}

[data-type="blockMath"],
[data-type="block-math"],
.tiptap-mathematics-render[data-type="block-math"],
.katex-display {
    display: block !important;
    text-align: center;
    width: 100%;
    max-width: 100%;
    /* Force LTR rendering */
    direction: ltr !important;
    unicode-bidi: isolate !important;
}

.katex {
    white-space: nowrap !important;
    pointer-events: none !important;
    direction: ltr !important;
    unicode-bidi: isolate !important;

}

.katex * {
    white-space: nowrap !important;
}

.math-node.ProseMirror-selectednode,
[data-type="inlineMath"].ProseMirror-selectednode,
[data-type="inline-math"].ProseMirror-selectednode,
[data-type="blockMath"].ProseMirror-selectednode,
[data-type="block-math"].ProseMirror-selectednode,
.tiptap-mathematics-render.ProseMirror-selectednode {
    outline: 2px solid var(--accent-color) !important;
    background-color: var(--block-selection-bg, rgba(0, 122, 255, 0.12)) !important;
    box-shadow: 0 0 0 1px var(--accent-color);
}

.math-node.ProseMirror-selectednode .katex,
[data-type="inlineMath"].ProseMirror-selectednode .katex,
[data-type="inline-math"].ProseMirror-selectednode .katex,
[data-type="blockMath"].ProseMirror-selectednode .katex,
[data-type="block-math"].ProseMirror-selectednode .katex,
.tiptap-mathematics-render.ProseMirror-selectednode .katex {
    background-color: transparent !important;
}

.math-error {
    color: #FF6B6B;
}

/* Fix for phantom line breaks after inline math nodes. */
.ProseMirror [data-type*="ath"]+br.ProseMirror-trailingBreak,
.ProseMirror [data-type*="math"]+br.ProseMirror-trailingBreak,
.ProseMirror [data-type="math"]+br.ProseMirror-trailingBreak {
    display: none !important;
    content: "" !important;
}

/* Ensure math nodes on mobile (inside .native-editor-container) have highly readable size */
.native-editor-container [data-type="math"] .katex,
.native-editor-container [data-type="inlineMath"] .katex,
.native-editor-container [data-type="inline-math"] .katex,
.native-editor-container [data-type="blockMath"] .katex,
.native-editor-container [data-type="block-math"] .katex,
.native-editor-container .tiptap-mathematics-render .katex,
.native-editor-container .math-node .katex {
    font-size: 1.15em !important;
}

/* Source: src/extensions/mermaid.css */
/* Mermaid Diagrams */
.mermaid-block {
    position: relative;
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
    padding: 1.5rem;
    border: 1px solid var(--border-color);
    border-radius: 12px;
    background-color: var(--bg-color);
    transition: all 0.2s ease;
    display: flex;
    flex-direction: column;
}

.mermaid-menu-btn {
    position: absolute;
    top: 8px;
    right: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: 6px;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    opacity: 0.1;
    transition: all 0.2s ease;
    z-index: 20;
}

.mermaid-block:hover .mermaid-menu-btn {
    opacity: 0.6;
}

.mermaid-menu-btn:hover {
    background-color: rgba(128, 128, 128, 0.1);
    opacity: 1 !important;
}

/* On mobile show it slightly more by default */
@media (max-width: 768px) {
    .mermaid-menu-btn {
        opacity: 0.4;
    }
}

.mermaid-block:hover {
    border-color: var(--accent-color);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
}

/* Scrollable preview wrapper — enables panning for wide/zoomed diagrams */
.mermaid-preview-scroll {
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    overscroll-behavior: contain;
    width: 100%;
    max-height: 500px;
    cursor: grab;
}

.mermaid-preview-scroll.is-panning {
    cursor: grabbing;
    user-select: none;
}

/* Custom scrollbar for mermaid preview — both axes */
.mermaid-preview-scroll::-webkit-scrollbar {
    width: 6px;
    height: 6px;
}

.mermaid-preview-scroll::-webkit-scrollbar-track {
    background: transparent;
    border-radius: 10px;
}

.mermaid-preview-scroll::-webkit-scrollbar-thumb {
    background: var(--border-color);
    border-radius: 10px;
}

.mermaid-preview-scroll::-webkit-scrollbar-thumb:hover {
    background: var(--accent-color);
}

.mermaid-preview {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100px;
    width: max-content;
    min-width: 100%;
    /* Add this to protect Mermaid's colors from Tailwind preflight in production */
    color: var(--text-color);
}

.mermaid-preview svg {
    height: auto;
}

/* Force Tailwind to leave Mermaid's internal SVG structure alone */
.mermaid-preview svg * {
    border-color: initial;
}

/* Zoom toolbar — sits below the preview, appears on hover */
.mermaid-zoom-toolbar {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 2px;
    padding: 2px;
    border-radius: 6px;
    background: color-mix(in srgb, var(--bg-color) 85%, transparent);
    border: 1px solid var(--border-color);
    width: fit-content;
    margin: 4px auto 0;
    opacity: 0;
    transition: opacity 0.2s ease;
    user-select: none;
}

.mermaid-block:hover .mermaid-zoom-toolbar {
    opacity: 1;
}

.mermaid-zoom-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 26px;
    height: 24px;
    border: none;
    border-radius: 4px;
    background: transparent;
    color: var(--text-color);
    cursor: pointer;
    transition: background-color 0.15s ease;
    padding: 0;
}

.mermaid-zoom-btn:hover {
    background-color: rgba(128, 128, 128, 0.15);
}

.mermaid-zoom-btn.mermaid-zoom-label {
    width: auto;
    padding: 0 6px;
    font-size: 11px;
    font-weight: 600;
    font-variant-numeric: tabular-nums;
    min-width: 42px;
    opacity: 0.7;
}

.mermaid-editor {
    display: flex;
    flex-direction: column;
    gap: 12px;
    width: 100%;
}

.mermaid-textarea {
    width: 100%;
    min-height: 180px;
    padding: 12px;
    border-radius: 8px;
    border: 1px solid var(--border-color);
    background-color: var(--code-block-bg);
    color: var(--text-color);
    font-family: 'FiraCode', monospace;
    font-size: 13px;
    line-height: 1.5;
    resize: vertical;
    outline: none;
}

.mermaid-textarea:focus {
    border-color: var(--accent-color);
    box-shadow: 0 0 0 2px color-mix(in srgb, var(--accent-color) 20%, transparent);
}

.mermaid-render-btn {
    align-self: flex-end;
    padding: 8px 16px;
    border-radius: 6px;
    background-color: var(--accent-color);
    color: white;
    border: none;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    transition: opacity 0.2s;
}

.mermaid-render-btn:hover {
    opacity: 0.9;
}

.mermaid-error {
    color: #FF6B6B;
    font-size: 14px;
    font-weight: 500;
    padding: 20px;
    border: 1px dashed #FF6B6B;
    border-radius: 8px;
    background-color: rgba(255, 107, 107, 0.05);
}

.mermaid-loading {
    color: var(--placeholder-color);
    font-size: 14px;
    font-style: italic;
    padding: 20px;
}


/* Source: src/extensions/quote.css */
.ProseMirror blockquote {
    /* border-inline-start: 3px solid var(--quote-border-color, var(--accent-color)); */
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
    padding-inline-start: 16px;
    padding-block: 4px;
    /* Reduced from 12px */
    opacity: 0.9;
    background-color: var(--quote-bg);
    border-start-end-radius: 4px;
    border-end-end-radius: 4px;
    transition: background-color 0.2s ease, border-color 0.2s ease;
}

.ProseMirror .quote-wrapper {
    position: relative;
    margin-bottom: var(--editor-paragraph-spacing);
    border-radius: 8px;
    transition: background-color 0.2s ease;
    /* Must NOT be overflow:hidden — that clips the absolutely-positioned drag handle */
    overflow: visible;
    /* Default background color derived from accent for better visibility */
    background-color: color-mix(in srgb, var(--accent-color), transparent 85%);
}

.ProseMirror .quote-wrapper blockquote {
    margin-bottom: 0;
    width: 100%;
    /* Remove original background so wrapper handles it and allows full width */
    background-color: transparent !important;
}

/* Three-dot menu button on quotes */
.quote-menu-btn {
    position: absolute;
    top: 10px;
    inset-inline-end: 6px;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 20px;
    border-radius: 4px;
    background: transparent;
    border: none;
    color: var(--text-color);
    cursor: pointer;
    opacity: 0.25;
    /* Always visible */
    transition: opacity 0.2s ease;
    z-index: 10;
}


.quote-menu-btn:hover {
    opacity: 0.7 !important;
}

@media (max-width: 768px) {
    .quote-menu-btn {
        top: 6px;
        inset-inline-end: 6px;
        width: 24px;
        height: 24px;
    }
}

/* Source: src/extensions/search.css */
/* ========================================
   Search Highlight Styles
   ======================================== */

.search-match {
    background-color: var(--accent-color);
    opacity: 0.4;
    border-radius: 2px;
}

.search-match-active {
    background-color: var(--accent-color);
    opacity: 0.7;
    border-radius: 2px;
    box-shadow: 0 0 0 2px var(--accent-color);
}


/* Source: src/extensions/table.css */
/* Table Styles */
.ProseMirror .tableWrapper {
    overflow-x: auto;
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
    -webkit-overflow-scrolling: touch;
    position: relative;
    /* Do NOT set width: 100% here — it creates a containing block that the
       browser uses to resolve percentage widths inside, which can clamp the
       table on narrow viewports. Let it size to its natural content width so
       overflow-x: auto actually has room to scroll. */
    display: block;
}

/* Custom scrollbar for tables */
.ProseMirror .tableWrapper::-webkit-scrollbar {
    height: 6px;
}

.ProseMirror .tableWrapper::-webkit-scrollbar-track {
    background: transparent;
}

.ProseMirror .tableWrapper::-webkit-scrollbar-thumb {
    background: var(--border-color);
    border-radius: 10px;
}

.ProseMirror table {
    border-collapse: separate;
    border-spacing: 0;
    /* width is set in px by updateColumns — do not set it in CSS */
    table-layout: fixed;
    border: 1px solid var(--border-color);
    border-radius: 10px;
    display: table;
    margin: 0;
    overflow: hidden;
    max-width: none;
}

.ProseMirror td,
.ProseMirror th {
    /* min-width is the floor; actual width comes from <col> elements set by
       updateColumns. Do NOT set width here — with table-layout: fixed the
       browser resolves column widths from <colgroup> first, then the first
       row's cells. A CSS width on td/th competes with <col> widths and wins
       on some WebViews, stretching the table to fill the viewport. */
    min-width: 32px;
    padding: 2px 4px;
    border-bottom: 1px solid var(--border-color);
    border-inline-end: 1px solid var(--border-color);
    text-align: start;
    vertical-align: top;
    position: relative;
    word-wrap: break-word;
    box-sizing: border-box;
}

/* Mobile: let the table bleed to the edge and scroll horizontally.
   No min-width, no width overrides — updateColumns owns all sizing. */
@media (max-width: 768px) {
    .ProseMirror .tableWrapper {
        margin-left: -16px;
        margin-right: -16px;
        padding-left: 16px;
        padding-right: 16px;
    }
}

.ProseMirror tr:last-child td,
.ProseMirror tr:last-child th {
    border-bottom: none;
}

.ProseMirror td:last-child,
.ProseMirror th:last-child {
    border-inline-end: none;
}

.ProseMirror td img {
    max-width: 100%;
    max-height: 350px;
    object-fit: contain;
}

.ProseMirror th {
    font-weight: 600;
    background-color: var(--table-header-bg);
}

.ProseMirror .selectedCell {
    background-color: rgba(0, 122, 255, 0.1) !important;
    box-shadow: inset 0 0 0 1000px rgba(0, 122, 255, 0.25) !important;
    outline: 2px solid var(--accent-color);
    outline-offset: -2px;
}

/* Stabilize borders during resizing */
.ProseMirror .column-resize-handle {
    position: absolute;
    inset-inline-end: -2px;
    top: 0;
    bottom: 0;
    width: 2px;
    background-color: var(--accent-color);
    pointer-events: none;
    z-index: 20;
}

.ProseMirror[dir="rtl"] .column-resize-handle {
    inset-inline-end: -2px;
    inset-inline-start: auto;
    transform: translateX(-1px);
}

.ProseMirror .resizing td,
.ProseMirror .resizing th {
    border-color: var(--border-color) !important;
}

.ProseMirror.resize-cursor {
    cursor: col-resize;
}

/* Source: src/extensions/task-list.css */
/* Task List */
.ProseMirror ul[data-type="taskList"] {
    list-style: none;
    padding-inline-start: 0;
    margin: 0;
    margin-bottom: var(--editor-paragraph-spacing);
}

.ProseMirror ul[data-type="taskList"] li {
    display: flex;
    align-items: flex-start;
    gap: 8px;
    margin: 0;
    margin-bottom: var(--editor-list-item-spacing);
}

.ProseMirror ul[data-type="taskList"] li>label {
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    height: calc(var(--editor-font-size) * var(--editor-line-height));
    margin-top: calc(var(--editor-paragraph-spacing) * 0.5);
    /* Better alignment with first line of text */
}

.ProseMirror ul[data-type="taskList"] li>label input[type="checkbox"] {
    width: 18px;
    height: 18px;
    appearance: none;
    -webkit-appearance: none;
    border: 2px solid var(--placeholder-color);
    border-radius: 4px;
    background: transparent;
    cursor: pointer;
    position: relative;
    display: block;
}

.ProseMirror ul[data-type="taskList"] li>label input[type="checkbox"]:checked {
    background: var(--accent-color);
    border-color: var(--accent-color);
}

.ProseMirror ul[data-type="taskList"] li>label input[type="checkbox"]:checked::after {
    content: '';
    position: absolute;
    left: 50%;
    top: 48%;
    width: 4px;
    height: 8px;
    border: solid white;
    border-width: 0 2px 2px 0;
    transform: translate(-50%, -50%) rotate(45deg);
}

.ProseMirror ul[data-type="taskList"] li>div {
    flex: 1;
}

.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) {
    color: color-mix(in srgb, var(--text-color) 50%, transparent);
    filter: grayscale(0.9) brightness(0.9);
}

.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) a {
    color: color-mix(in srgb, var(--accent-color) 50%, transparent);
}

/* Dim images and other media elements, as they don't have text selection */
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) img,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) video,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) audio,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) iframe,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) [data-type*="math"] {
    opacity: 0.5;
}

/* Dim elements with explicit colors, highlights, or custom backgrounds as they bypass inherited text color */
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) code,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) mark,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) span[class*="tc-"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) span[class*="hl-"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) span[style*="color"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) span[style*="background-color"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) [data-color] {
    opacity: 0.5;
}

.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>div>*:not(ul[data-type="taskList"]) ::selection {
    background-color: var(--accent-color);
    color: white;
}

/* ─── Print / Export: clean serialized format (no label/div wrappers) ─── */
/* In exported HTML, children like <p> are direct children of <li> */

.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) {
    color: color-mix(in srgb, var(--text-color) 50%, transparent);
    filter: grayscale(0.9) brightness(0.9);
}

.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) a {
    color: color-mix(in srgb, var(--accent-color) 50%, transparent);
}

.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) img,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) video,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) audio,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) iframe,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) [data-type*="math"] {
    opacity: 0.5;
}

.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) code,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) mark,
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) span[class*="tc-"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) span[class*="hl-"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) span[style*="color"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) span[style*="background-color"],
.ProseMirror ul[data-type="taskList"] li[data-checked="true"]>*:not(label):not(div):not(ul[data-type="taskList"]) [data-color] {
    opacity: 0.5;
}


`;
