import {
    Baseline,
    Bold,
    CheckSquare,
    ChevronLeft,
    ChevronRight,
    Code,
    FilePlusCorner,
    Highlighter,
    Indent,
    Italic,
    Layout,
    Link,
    List,
    ListOrdered,
    MessageSquareQuote,
    MoreHorizontal,
    Outdent,
    Paperclip,
    Plus,
    Redo2,
    Sigma,
    SquarePlay,
    SquareTerminal,
    Strikethrough,
    Table,
    Type,
    Underline,
    Undo2,
    Workflow
} from 'lucide-react';

export const EditorIcons = {
    Baseline,
    Bold,
    CheckSquare,
    TaskList: CheckSquare,
    ChevronLeft,
    ChevronRight,
    Code,
    Details: FilePlusCorner,
    FileInput: FilePlusCorner,
    Highlighter,
    Indent,
    Italic,
    Blocks: Layout,
    MessageSquare: Layout,
    Link,
    List,
    BulletList: List,
    ListOrdered,
    OrderedList: ListOrdered,
    Quote: MessageSquareQuote,
    More: MoreHorizontal,
    Outdent,
    File: Paperclip,
    Plus,
    Redo: Redo2,
    Sigma,
    Math: Sigma,
    SquareCode: SquareTerminal,
    CodeBlock: SquareTerminal,
    Strike: Strikethrough,
    Strikethrough,
    Table,
    Type,
    Heading: Type,
    Underline,
    Undo: Undo2,
    Youtube: SquarePlay,
    Mermaid: Workflow
};

export const DesktopIconMap: Record<string, any> = {
    'heading': EditorIcons.Heading,
    'h1': EditorIcons.Heading,
    'h2': EditorIcons.Heading,
    'h3': EditorIcons.Heading,
    'format': EditorIcons.Baseline,
    'bold': EditorIcons.Bold,
    'italic': EditorIcons.Italic,
    'underline': EditorIcons.Underline,
    'strike': EditorIcons.Strike,
    'list': EditorIcons.List,
    'bulletList': EditorIcons.BulletList,
    'orderedList': EditorIcons.OrderedList,
    'taskList': EditorIcons.CheckSquare,
    'blocks': EditorIcons.Blocks,
    'quote': EditorIcons.Quote,
    'codeblock': EditorIcons.CodeBlock,
    'code': EditorIcons.Code,
    'details': EditorIcons.Details,
    'plus': EditorIcons.Plus,
    'math': EditorIcons.Math,
    'file': EditorIcons.File,
    'link': EditorIcons.Link,
    'youtube': EditorIcons.Youtube,
    'table': EditorIcons.Table,
    'mermaid': EditorIcons.Mermaid,
};
